export * from "./types";

export { AuthAPI } from "./account/auth";
export { GuestAPI } from "./account/guest";
export { MeAPI } from "./account/me";
export { UploadAPI } from "./common/upload";
export { WebsocketAPI } from "./common/websocket";
export { ArticleAPI } from "./content/article";
export { CategoryAPI } from "./content/category";
export { TagAPI } from "./content/tag";
export { DefaultAPI } from "./default";
export { CommentAPI } from "./discussion/comment";
export { MessageAPI } from "./discussion/message";
export { TalkAPI } from "./discussion/talk";
export { AlbumAPI } from "./media/album";
export { PhotoAPI } from "./media/photo";
export { ConfigAPI } from "./site/config";
export { FriendAPI } from "./site/friend";
export { HomeAPI } from "./site/home";
export { PageAPI } from "./site/page";
